server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:

        - id: micro1
          uri: lb://Micro1
          predicates:
            - Path=/micro1

        - id: micro2
          uri: lb://Micro2
          predicates:
            - Path=/micro2


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

